//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/_Project/InputActions/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""LandMap"",
            ""id"": ""4facb56b-3ee2-4408-983b-4ad48960a1cc"",
            ""actions"": [
                {
                    ""name"": ""LandActions"",
                    ""type"": ""Button"",
                    ""id"": ""b2af32b6-9bc3-4343-b03e-3888678b9bb3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""319f82f9-d4ad-4b2c-95cf-d6ec93305f6b"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LandActions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // LandMap
        m_LandMap = asset.FindActionMap("LandMap", throwIfNotFound: true);
        m_LandMap_LandActions = m_LandMap.FindAction("LandActions", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // LandMap
    private readonly InputActionMap m_LandMap;
    private ILandMapActions m_LandMapActionsCallbackInterface;
    private readonly InputAction m_LandMap_LandActions;
    public struct LandMapActions
    {
        private @PlayerInputs m_Wrapper;
        public LandMapActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @LandActions => m_Wrapper.m_LandMap_LandActions;
        public InputActionMap Get() { return m_Wrapper.m_LandMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LandMapActions set) { return set.Get(); }
        public void SetCallbacks(ILandMapActions instance)
        {
            if (m_Wrapper.m_LandMapActionsCallbackInterface != null)
            {
                @LandActions.started -= m_Wrapper.m_LandMapActionsCallbackInterface.OnLandActions;
                @LandActions.performed -= m_Wrapper.m_LandMapActionsCallbackInterface.OnLandActions;
                @LandActions.canceled -= m_Wrapper.m_LandMapActionsCallbackInterface.OnLandActions;
            }
            m_Wrapper.m_LandMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LandActions.started += instance.OnLandActions;
                @LandActions.performed += instance.OnLandActions;
                @LandActions.canceled += instance.OnLandActions;
            }
        }
    }
    public LandMapActions @LandMap => new LandMapActions(this);
    public interface ILandMapActions
    {
        void OnLandActions(InputAction.CallbackContext context);
    }
}
